Repository AMastryukov/LD51, pull requests merged in 2022-10, with the labels that each got.

#48 Game manager
  Source/Assets/Prefabs/Managers.meta
  Source/Assets/Prefabs/Managers/Game Manager.prefab
  Source/Assets/Prefabs/Managers/Game Manager.prefab.meta
  Source/Assets/Scenes/George.meta
  Source/Assets/Scenes/George/GameManagerTester.unity
  Source/Assets/Scenes/George/GameManagerTester.unity.meta
  Source/Assets/Scripts/Enums.meta
  Source/Assets/Scripts/Enums/Bonuses.cs
  Source/Assets/Scripts/Enums/Bonuses.cs.meta
  Source/Assets/Scripts/GameManager.cs
  Source/Assets/Scripts/Tests.meta
  Source/Assets/Scripts/Tests/GameManagerTester.cs
  Source/Assets/Scripts/Tests/GameManagerTester.cs.meta
Labels: High Priority, Code

#73 Player buffs
  Source/Assets/Scripts/Tests/TestBarricade.cs
Labels: High Priority, Code

#118 Placement fix
  Source/Assets/Prefabs/Traps/BarbedWireItem.prefab
  Source/Assets/Prefabs/Traps/LandMineItem.prefab
  Source/Assets/Prefabs/Traps/TurretItem.prefab
  Source/Assets/Scripts/Objects/ProjectedItem.cs
Labels: Bug, Medium Priority

#123 Room captured outline prefabs, models, textures and updated code
  Source/Assets/Models/Johnnie/bedroomoutline.fbx
  Source/Assets/Models/Johnnie/bedroomoutline.fbx.meta
  Source/Assets/Models/Johnnie/diningroomoutline.fbx
  Source/Assets/Models/Johnnie/diningroomoutline.fbx.meta
  Source/Assets/Models/Johnnie/foyeroutline.fbx
  Source/Assets/Models/Johnnie/foyeroutline.fbx.meta
  Source/Assets/Models/Johnnie/garageoutline.fbx
  Source/Assets/Models/Johnnie/garageoutline.fbx.meta
  Source/Assets/Models/Johnnie/gymoutline.fbx
  Source/Assets/Models/Johnnie/gymoutline.fbx.meta
  Source/Assets/Models/Johnnie/kitchenoutline.fbx
  Source/Assets/Models/Johnnie/kitchenoutline.fbx.meta
  Source/Assets/Prefabs/Room Captured Notifiers.prefab
  Source/Assets/Prefabs/Room Captured Notifiers.prefab.meta
  Source/Assets/Scripts/Room.cs
  Source/Assets/Textures/Johnnie.meta
  Source/Assets/Textures/Johnnie/Materials.meta
  Source/Assets/Textures/Johnnie/Materials/bedroom 1.mat
  Source/Assets/Textures/Johnnie/Materials/bedroom 1.mat.meta
  Source/Assets/Textures/Johnnie/Materials/diningroom 1.mat
  Source/Assets/Textures/Johnnie/Materials/diningroom 1.mat.meta
  Source/Assets/Textures/Johnnie/Materials/entrancefoyer 1.mat
  Source/Assets/Textures/Johnnie/Materials/entrancefoyer 1.mat.meta
  Source/Assets/Textures/Johnnie/Materials/garage 1.mat
  Source/Assets/Textures/Johnnie/Materials/garage 1.mat.meta
  Source/Assets/Textures/Johnnie/Materials/gym 1.mat
  Source/Assets/Textures/Johnnie/Materials/gym 1.mat.meta
  Source/Assets/Textures/Johnnie/Materials/kitchen 1.mat
  Source/Assets/Textures/Johnnie/Materials/kitchen 1.mat.meta
  Source/Assets/Textures/Johnnie/bedroom.png
  Source/Assets/Textures/Johnnie/bedroom.png.meta
  Source/Assets/Textures/Johnnie/diningroom.png
  Source/Assets/Textures/Johnnie/diningroom.png.meta
  Source/Assets/Textures/Johnnie/entrancefoyer.png
  Source/Assets/Textures/Johnnie/entrancefoyer.png.meta
  Source/Assets/Textures/Johnnie/garage.png
  Source/Assets/Textures/Johnnie/garage.png.meta
  Source/Assets/Textures/Johnnie/gym.png
  Source/Assets/Textures/Johnnie/gym.png.meta
  Source/Assets/Textures/Johnnie/kitchen.png
  Source/Assets/Textures/Johnnie/kitchen.png.meta
Labels: Low Priority, 2D Asset, 3D Asset, Integration, Code, Art

#125 Buff related fixes
  Source/Assets/Data/Buffs/Damage.asset
  Source/Assets/Data/Buffs/Regen.asset
  Source/Assets/Data/Buffs/Repairs.asset
  Source/Assets/Data/Buffs/Speed.asset
  Source/Assets/Data/Buffs/Stamina.asset
  Source/Assets/Prefabs/Player.prefab
  Source/Assets/Scripts/Player/Player.cs
  Source/Assets/Scripts/Player/PlayerBuffsManager.cs
  Source/Assets/Scripts/Room.cs
  Source/Assets/Sprites/User Interface/Icons/Buffs/barricadebuff.psd.meta
  Source/Assets/Sprites/User Interface/Icons/Buffs/damagereductionbuff.psd.meta
  Source/Assets/Sprites/User Interface/Icons/Buffs/extradamagebuff.psd.meta
  Source/Assets/Sprites/User Interface/Icons/Buffs/playermovementbuff.psd.meta
  Source/Assets/Sprites/User Interface/Icons/Buffs/regenhpbuff.psd.meta
  Source/Assets/Sprites/User Interface/Icons/Buffs/staminabuff.psd.meta
Labels: Bug
